### ISSUE TITLE
JOSS Submission Review (Reviewer 2): Software paper

### ISSUE THREAD

**Issue by damar-wicaksono** [ERMETE-Lab/ROSE-pyforce#10]
This issue is related to the [JOSS submission review](https://github.com/openjournals/joss-reviews/issues/6950).

Below are my remarks and suggestions regarding the software paper. Just let me know if further clarifications are need. Thank you!

## Summary

- [x] I think the first paragraph of the next section ("Statement of need") should be switched as the "Summary" of the paper as it better describes the high-level functionality and purpose of the package. Furthermore, the summary should also include the target audience of the package which the authors have also stated in the last paragraph of the next section.
- [x] "_...more hostile environment compared to..._": Perhaps simply "than" is better than "compared to".
- [x] "_...and able to combine together different sources..._": I think "together" is unnecessary.
- [x] "_...and real data (i.e., measurements)..._": Perhaps to be succinct, this can be written simply as "measurement data"
- [x] "_...the dynamics of un-observable complex field..._": Somewhere else in the paper "non-observable" is used, perhaps simply pick one?

## Statement of need

- [x] As noted above, I think the first paragraph should be switched with the paragraph in "Summary". The paragraph in Summary better describes the need that is served by the package.
- [x] Because pyforce is an abbreviation perhaps the expanded term should appear directly after "_pyforce_"
- [x] "_...mainly for the Nuclear Engineering world._": Perhaps "in" instead of "for"
- [x] "_...Nuclear Engineering..._": Is the capitalization really necessary?
- [x] "_The package is part of the ROSE..._": Is there a reference to ROSE perhaps a link or a document?
- [x] "_at reducing..., at searching... and at integrating..._": I think there is no need to repeat the preposition "at" due to already parallel structure
- [x] Figure 1 should be better clarified by the second paragraph in this section; the figure contains mathematical symbols and notations that should be defined briefly and explicitly in the passage (if these symbols and notations are kept in the end). For instance, reading the paragraph it is not clear the starting point of the whole scheme (is it the field according to the full order model, or something else?).
- [x] I would suggest that the list of implemented features are rewritten (perhaps in tabular form) to correspond to the figure better; which ones belong specifically to the offline and online phase, just the offline phase, or just the online phase. The list structure gives the impression that these features serve similar exchangeable purposes.
- [x] "_...either regularised with Tikhonov or not..._": Perhaps it would be better to write as "either with or without Tikhonov's regularisation"
- [x] "_...for the Online Phase_": Before there was no capitalization for "Online Phase". Is the capitalization intentional?

## Contribution and authorship

Currently, the paper list three authors, namely S. Riva, C. Introini, and A. Cammi.  Looking at the commit contributions [page](https://github.com/ERMETE-Lab/ROSE-pyforce/graphs/contributors), I've seen two contributors have made commits. As @Steriva is S. Riva so the question regarding "Contribution and Authorship" is settled. Is [Neko-tan](https://github.com/Neko-tan) also one of the authors?

Related to the paper, I would like to also suggest including a list of the contributions of each author separately in the paper.
Some JOSS papers (for example, [here](https://joss.theoj.org/papers/10.21105/joss.05873)) adopted the [CRediT](https://credit.niso.org/) taxonomy to clarify those roles.
Perhaps the authors would consider adding such section to the paper?

**Comment by Steriva** [comment]
Thank you @damar-wicaksono for the insightful comments (including #8 and #9).
In the coming weeks, I'll update the repository following your suggestions.

Just a quick note about the authors: @Neko-tan is Carolina Introini, whereas A. Cammi is the professor supervising all the activities: I'll add the CRediT taxonomy to the paper to clarify the roles.

Thank you again!

**Comment by Steriva** [comment]
# Response Letter: Software Paper

Thank you very much for the useful comments and suggestions. Here are listed the response and the changes made to the joss-paper.

The changes are reported in pull request #12.

## Summary

1. *I think the first paragraph of the next section ("Statement of need") should be switched as the "Summary" of the paper as it better describes the high-level functionality and purpose of the package. Furthermore, the summary should also include the target audience of the package which the authors have also stated in the last paragraph of the next section.*
   - [x] The paragraphs have been switched and more insights about the target audience of the package are added.
2. *"...more hostile environment compared to...": Perhaps simply "than" is better than "compared to".*
   - [x] Fixed
3. *"...and able to combine together different sources...": I think "together" is unnecessary."*
   - [x] Fixed
4. *"...and real data (i.e., measurements)...": Perhaps to be succinct, this can be written simply as "measurement data"*
   - [x] Changed to measurements data (i.e., local evaluations of quantities of interest).
5. *"...the dynamics of un-observable complex field...": Somewhere else in the paper "non-observable" is used, perhaps simply pick one?*
   - [x] Fixed.

## Statement of need

1. *Because pyforce is an abbreviation perhaps the expanded term should appear directly after "pyforce"*
   - [x] Changed
2. *"...mainly for the Nuclear Engineering world.": Perhaps "in" instead of "for"*
   - [x] Fixed
3. *"...Nuclear Engineering...": Is the capitalization really necessary?*
   - [x] No, it isn't: changed
4. *"The package is part of the ROSE...": Is there a reference to ROSE perhaps a link or a document?*
   - [x] Some comments about ROSE (an acronym used within the ERMETE-Lab to refer to ROM related applications to multi-physics for nuclear reactors).
5. *"at reducing..., at searching... and at integrating...": I think there is no need to repeat the preposition "at" due to already parallel structure*
   - [x] Fixed
6. *Figure 1 should be better clarified by the second paragraph in this section; the figure contains mathematical symbols and notations that should be defined briefly and explicitly in the passage (if these symbols and notations are kept in the end). For instance, reading the paragraph it is not clear the starting point of the whole scheme (is it the field according to the full order model, or something else?).*
   - [x] The description of the Figure has been greatly expanded, the Figure itself has been updated to reflect the one present on the README of the Github repo.
7. *I would suggest that the list of implemented features are rewritten (perhaps in tabular form) to correspond to the figure better; which ones belong specifically to the offline and online phase, just the offline phase, or just the online phase. The list structure gives the impression that these features serve similar exchangeable purposes.*
   - [x] Implemented
8. *"...either regularised with Tikhonov or not...": Perhaps it would be better to write as "either with or without Tikhonov's regularisation"*
   - [x] Changed
9. *"...for the Online Phase": Before there was no capitalization for "Online Phase". Is the capitalization intentional?*
   - [x] No, it isn't: changed

## Contribution and authorship

[CRediT](https://credit.niso.org/) taxonomy has been added to clarify the roles, reported below.

- Stefano Riva: Conceptualization, Data curation, Formal analysis, Software, Visualization, Writing – original draft
- Carolina Introini: Conceptualization, Formal analysis, Software, Supervision, Writing – review & editing
- Antonio Cammi: Conceptualization, Project administration, Resources, Supervision, Writing – review & editing

**Comment by damar-wicaksono** [comment]
@Steriva: Thank you very much for taking the time going through my comments! So that I can verify the changes and close this issue, is the updated draft can already be built into a PDF file from the [JOSS review page](https://github.com/openjournals/joss-reviews/issues/6950)? I'm asking because it seems that the pull request is still open...

**Comment by Steriva** [comment]
I've just merged the pull request into the main branch. Thank you very much for all the valuable comments!

**Comment by damar-wicaksono** [comment]
Thank you again for revising the paper! I went through the latest draft and confirmed that my previous remarks have been addressed.

There are a couple additional things that you might want to consider before I can close this issue.

## Statement of need

- [x] l. 33 "_...whereas the latter is cheap from the computational point of view..._": Why not use the previous construction of "computationally expensive" and state simply "computational cheap"?
- [x] l. 34 "_...point of view and allows to have quick and reliable evaluations..._": If I'm not wrong "allow to" needs a direct object so either "allows one to have quick" or change the preposition into "allows for quick and reliable evaluations..." or change the verb to, say, "enable".
- [x] l. 36 "_During the offline..._": Perhaps start a new paragraph here to have a clear separation from what came before (general idea of offline/online phase) and what is coming after (the online phase).
- [x] l. 40 "_...reduced representation through a set of basis functions_ $`\{ \psi_n(\boldsymbol{x}) \}`$...": maybe add directly after the set "of size $N$", i.e., "_...through a set of basis functions_ $`\{ \psi_n(\boldsymbol{x}) \}`$ _of size_ $N$..."
- [x] l. 41 typo "decresed"
- [x] l. 41, similar comment as above regarding "allow to" without a direct object
- [x] l. 44 "_...allows for the search of the optimal positions of sensors...in a more efficient manner_": I think "allows for" is correct but  it should be "search for" instead of "search of" in the present usage. So perhaps: "_...allows for efficiently searching for optimal sensor placements in the physical domain._"?
- [x] l. 46 "_All these steps are performed during the offline phase,..._": In my opinion this is not necessary, simply start with this new paragraph the online phase.
- [x] l. 46 "_..., the online phase aim consists in obtaining..._": Why not "the online phase aims to obtain..."
- [x] l. 48-49 "_The DDROM online takes place which produces a novel set of reduced variables, $`\alpha^*`$, and then computing an improved reconstructed state $`\hat{u}_{\mathrm{DDROM}}`$ through a decoding step from the low dimensional state to the high dimensional one._": I find this hard to read. Perhaps as an alternative:

> "The DDROM online phase produces a new set of reduced variables (_are these "coefficients", as in the above, or "variables"?_), $`\alpha^*`$, and then  computes an improved reconstructed state $`\hat{u}_{\mathrm{DDROM}}`$ through a decoding step that transforms the low-dimensional representation to the high-dimensional one."

And with that, I have no further comments regarding on the draft manuscript. Please let me know if you need clarifications. Thank you!

**Comment by Steriva** [comment]
Thanks for the comments: all the changes have been implemented and merged into the main branch with pull request #13.

The draft paper has been generated with [this action](https://github.com/ERMETE-Lab/ROSE-pyforce/actions/runs/10873140557).

**Comment by damar-wicaksono** [comment]
Thank you very much for the revision! I confirm that the points I've raised have been resolved.

One additional very minor issue that you might want to correct is line 56 on page 3: "_...and its scope of application is not only restricted to the **Nuclear Engineering** world..._" which to be consistent with the previous usage should not be capitalized.

I'm closing this issue now.... Thank you!
